# Generated by Django 2.2 on 2020-03-31 15:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RosRouter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip地址')),
                ('ros_user', models.CharField(default='', max_length=100, verbose_name='ros用户')),
                ('ros_pwd', models.CharField(default='', max_length=100, verbose_name='ros密码')),
            ],
            options={
                'verbose_name': 'ros设备',
                'verbose_name_plural': 'ros设备',
                'db_table': 'ros_router',
            },
        ),
        migrations.CreateModel(
            name='VPNInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vpn_user', models.CharField(default='', max_length=60, verbose_name='VPN用户名')),
                ('vpn_pwd', models.CharField(default='', max_length=60, verbose_name='VPN密码')),
                ('status', models.BooleanField(default=False, verbose_name='VPN状态')),
                ('ros', models.ForeignKey(blank=True, on_delete=False, to='network.RosRouter', verbose_name='归属ros路由器')),
            ],
            options={
                'verbose_name': 'VPN信息',
                'verbose_name_plural': 'VPN信息',
                'db_table': 'vpn_info',
            },
        ),
        migrations.CreateModel(
            name='UserManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.ManyToManyField(blank=True, to='network.RosRouter', verbose_name='下属ros路由器')),
                ('user', models.ForeignKey(blank=True, on_delete=False, to=settings.AUTH_USER_MODEL, verbose_name='系统用户')),
            ],
            options={
                'verbose_name': '用户管理设备',
                'verbose_name_plural': '用户管理设备',
                'db_table': 'user_manage',
            },
        ),
    ]
