# Generated by Django 2.2 on 2020-04-04 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpninfo',
            name='online_time',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='在线时间'),
        ),
    ]
