# Generated by Django 2.2 on 2020-04-04 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_vpninfo_online_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vpninfo',
            old_name='online_time',
            new_name='up_time',
        ),
    ]
