# Generated by Django 2.2 on 2020-04-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20200405_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermanage',
            name='device',
        ),
        migrations.AddField(
            model_name='usermanage',
            name='device',
            field=models.ForeignKey(blank=True, default=1, on_delete=False, to='network.RosRouter', verbose_name='下属ros路由器'),
            preserve_default=False,
        ),
    ]
