# Generated by Django 2.2 on 2020-04-09 13:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('network', '0004_auto_20200409_2126'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usermanage',
            unique_together={('user', 'device')},
        ),
    ]
