# Generated by Django 2.2 on 2020-04-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_vpninfo_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=60, verbose_name='按钮名称')),
                ('port', models.CharField(default='', max_length=60, verbose_name='端口号')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='ip')),
            ],
            options={
                'verbose_name': '按钮',
                'verbose_name_plural': '按钮',
                'db_table': 'button',
            },
        ),
        migrations.AlterField(
            model_name='vpninfo',
            name='remark',
            field=models.CharField(default='', max_length=400, verbose_name='备注信息'),
        ),
    ]
