# Generated by Django 2.2 on 2020-06-14 15:00

import cidrfield.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_auto_20200601_2220'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='button',
            options={'verbose_name': '路由与接口功能', 'verbose_name_plural': '路由与接口功能'},
        ),
        migrations.AlterField(
            model_name='button',
            name='ip',
            field=cidrfield.models.IPNetworkField(blank=True, null=True, verbose_name='ip'),
        ),
    ]
