# Generated by Django 2.2 on 2020-07-05 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_auto_20200619_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='ip',
            field=models.CharField(max_length=100, null=True, verbose_name='路由地址'),
        ),
    ]
