# Generated by Django 2.2 on 2020-07-10 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_auto_20200705_1717'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='button',
            options={'verbose_name': '路由出口优化', 'verbose_name_plural': '路由出口优化'},
        ),
        migrations.AlterModelOptions(
            name='vpninfo',
            options={'verbose_name': '远程办公服务', 'verbose_name_plural': '远程办公服务'},
        ),
    ]
