# Generated by Django 2.2 on 2020-07-18 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_auto_20200710_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='button',
            name='name',
        ),
        migrations.RemoveField(
            model_name='button',
            name='port',
        ),
    ]
