# Generated by Django 2.2 on 2020-07-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_auto_20200718_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='button',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=False, to='network.RosRouter', verbose_name='归属ros路由器'),
        ),
    ]
