# Generated by Django 2.2 on 2020-07-23 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0018_auto_20200721_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_time', models.DateTimeField(verbose_name='时间测试')),
            ],
        ),
    ]
