# Generated by Django 2.2 on 2020-07-25 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0019_testmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolDownload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('software', models.CharField(default='', max_length=400, verbose_name='软件名')),
            ],
            options={
                'verbose_name': '辅助工具下载',
                'verbose_name_plural': '辅助工具下载',
                'db_table': 'software_download',
            },
        ),
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
