# Generated by Django 2.2 on 2020-08-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0020_auto_20200725_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vpn_ip', models.GenericIPAddressField(verbose_name='VPN设备ip')),
                ('uptime', models.CharField(max_length=100, verbose_name='在线时间')),
            ],
            options={
                'verbose_name': '总头控制',
                'verbose_name_plural': '总头控制',
                'db_table': 'center',
            },
        ),
    ]
